"use client";

import * as Dialog from "@radix-ui/react-dialog";
import { FileJson, HardDrive, Trash2, Upload, X } from "lucide-react";
import { ChangeEvent, useMemo, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { ImportSummary } from "@/components/import/import-summary";
import { JsonEditor } from "@/components/import/json-editor";
import { parseFinancialJson } from "@/lib/financial-parser";
import { sampleJson } from "@/lib/sample-data";
import type { ImportResult, Transaction } from "@/lib/types";

export function JsonImportDialog({ open, onOpenChange, onImport, embedded = false }: { open: boolean; onOpenChange: (open: boolean) => void; onImport: (transactions: Transaction[], result: ImportResult) => void; embedded?: boolean }) {
  const [text, setText] = useState(""); const fileRef = useRef<HTMLInputElement>(null);
  const analysis = useMemo(() => { if (!text.trim()) return { result: null as ImportResult | null, error: "" }; try { return { result: parseFinancialJson(text), error: "" }; } catch (error) { return { result: null, error: error instanceof Error ? error.message : "JSON نامعتبر است" }; } }, [text]);
  const readFile = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 20 * 1024 * 1024) { setText(""); return; } const reader = new FileReader(); reader.onload = () => setText(String(reader.result ?? "")); reader.readAsText(file); event.target.value = ""; };
  const content = <div className={embedded ? "card p-4 md:p-6" : ""}><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><span className="soft-accent flex h-9 w-9 items-center justify-center rounded-[10px]"><FileJson size={18}/></span><div><Dialog.Title className="font-bold">ورود اطلاعات مالی</Dialog.Title><Dialog.Description className="mt-0.5 text-xs text-[var(--muted)]">فایل JSON یا متن خروجی hledger را وارد کنید.</Dialog.Description></div></div></div>{!embedded && <Dialog.Close asChild><button className="icon-button"><X size={18}/></button></Dialog.Close>}</div><div className="mt-5 flex flex-wrap gap-2"><input ref={fileRef} type="file" accept="application/json,.json" className="hidden" onChange={readFile}/><Button variant="outline" size="sm" onClick={() => fileRef.current?.click()}><Upload size={14}/>انتخاب فایل</Button><Button variant="outline" size="sm" onClick={() => setText(sampleJson())}><FileJson size={14}/>اطلاعات نمونه</Button><Button variant="ghost" size="sm" disabled={!text} onClick={() => setText("")}><Trash2 size={14}/>پاک کردن متن</Button></div><div className="mt-5"><JsonEditor value={text} onChange={setText} error={analysis.error}/></div>{analysis.result && <div className="mt-4"><ImportSummary result={analysis.result}/></div>}<div className="mt-4 flex items-center gap-2 rounded-[10px] border bg-[var(--surface-muted)] p-3 text-[11px] text-[var(--muted)]"><HardDrive size={16} className="shrink-0 text-[var(--accent)]"/>اطلاعات مالی شما فقط روی همین دستگاه ذخیره می‌شود و به هیچ سروری ارسال نمی‌شود.</div><div className="mt-5 flex justify-end gap-2">{!embedded && <Dialog.Close asChild><Button variant="outline">انصراف</Button></Dialog.Close>}<Button disabled={!analysis.result?.valid.length} onClick={() => { if (!analysis.result) return; onImport(analysis.result.valid, analysis.result); if (!embedded) onOpenChange(false); }}>ورود {analysis.result?.valid.length ? analysis.result.valid.length.toLocaleString("fa-IR") : ""} تراکنش</Button></div></div>;
  if (embedded) return content;
  return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-40 bg-black/45"/><Dialog.Content dir="rtl" className="fixed left-1/2 top-1/2 z-50 max-h-[92dvh] w-[calc(100%-24px)] max-w-3xl -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-[16px] border bg-[var(--surface)] p-4 text-[var(--foreground)] shadow-2xl md:p-6">{content}</Dialog.Content></Dialog.Portal></Dialog.Root>;
}
