import { Search } from "lucide-react";
import type { Filters, TransactionType } from "@/lib/types";
import { TYPE_LABELS } from "@/lib/account-parser";

export function TransactionFilters({ filters, setFilters, accounts, categories }: { filters: Filters; setFilters: (filters: Filters) => void; accounts: string[]; categories: { key: string; label: string }[] }) {
  const update = <K extends keyof Filters>(key: K, value: Filters[K]) => setFilters({ ...filters, [key]: value });
  return <div className="grid gap-2 border-b p-4 md:grid-cols-2 xl:grid-cols-[minmax(240px,1fr)_repeat(4,auto)]"><label className="relative"><Search size={15} className="absolute right-3 top-3 text-[var(--muted)]"/><input value={filters.search} onChange={(e) => update("search", e.target.value)} placeholder="جستجو در شرح یا حساب..." className="h-10 w-full rounded-[10px] border bg-[var(--surface)] pr-9 pl-3 text-xs outline-none focus:border-[var(--accent)]"/></label><select value={filters.type} onChange={(e) => update("type", e.target.value as TransactionType | "all")} className="h-10 rounded-[10px] border bg-[var(--surface)] px-3 text-xs"><option value="all">همه نوع‌ها</option>{Object.entries(TYPE_LABELS).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select><select value={filters.account} onChange={(e) => update("account", e.target.value)} className="h-10 max-w-[200px] rounded-[10px] border bg-[var(--surface)] px-3 text-xs"><option value="all">همه حساب‌ها</option>{accounts.map((a) => <option key={a}>{a}</option>)}</select><select value={filters.category} onChange={(e) => update("category", e.target.value)} className="h-10 rounded-[10px] border bg-[var(--surface)] px-3 text-xs"><option value="all">همه دسته‌ها</option>{categories.map((c) => <option key={c.key} value={c.key}>{c.label}</option>)}</select><select value={filters.currency} onChange={(e) => update("currency", e.target.value as CurrencyUnit | "all")} className="h-10 rounded-[10px] border bg-[var(--surface)] px-3 text-xs"><option value="all">همه واحدها</option><option value="IRT">تومان</option><option value="IRR">ریال</option></select></div>;
}

import type { CurrencyUnit } from "@/lib/types";
