"use client";

import { Database, Download, Moon, ShieldCheck, Sun, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { Transaction } from "@/lib/types";

export function SettingsView({ transactions, dark, setDark, onClear }: { transactions: Transaction[]; dark: boolean; setDark: (v: boolean) => void; onClear: () => void }) {
  const exportData = () => { const blob = new Blob([JSON.stringify(transactions.map((t) => t.raw), null, 2)], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "poya-transactions.json"; link.click(); URL.revokeObjectURL(link.href); };
  return <div className="grid gap-4 xl:grid-cols-2"><section className="card p-5"><div className="flex items-center gap-3"><span className="soft-accent flex h-10 w-10 items-center justify-center rounded-[10px]"><Moon size={18}/></span><div><h2 className="font-bold">ظاهر برنامه</h2><p className="mt-1 text-xs text-[var(--muted)]">حالت مناسب محیط خود را انتخاب کنید.</p></div></div><div className="mt-5 grid grid-cols-2 gap-3"><button onClick={() => setDark(false)} className={`flex items-center justify-center gap-2 rounded-[11px] border p-4 text-sm ${!dark ? "border-[var(--accent)] bg-[var(--accent-soft)] text-[var(--accent-strong)]" : ""}`}><Sun size={18}/>روشن</button><button onClick={() => setDark(true)} className={`flex items-center justify-center gap-2 rounded-[11px] border p-4 text-sm ${dark ? "border-[var(--accent)] bg-[var(--accent-soft)] text-[var(--accent-strong)]" : ""}`}><Moon size={18}/>تیره</button></div></section><section className="card p-5"><div className="flex items-center gap-3"><span className="soft-accent flex h-10 w-10 items-center justify-center rounded-[10px]"><Database size={18}/></span><div><h2 className="font-bold">داده‌های محلی</h2><p className="mt-1 text-xs text-[var(--muted)]">{transactions.length.toLocaleString("fa-IR")} تراکنش در این مرورگر ذخیره شده است.</p></div></div><div className="mt-5 flex flex-wrap gap-2"><Button variant="outline" onClick={exportData} disabled={!transactions.length}><Download size={16}/>دریافت نسخه پشتیبان</Button><Button variant="danger" onClick={() => { if (confirm("تمام اطلاعات محلی حذف شود؟ این کار قابل بازگشت نیست.")) onClear(); }} disabled={!transactions.length}><Trash2 size={16}/>حذف تمام اطلاعات محلی</Button></div></section><section className="card p-5 xl:col-span-2"><div className="flex items-center gap-3"><span className="soft-accent flex h-10 w-10 items-center justify-center rounded-[10px]"><ShieldCheck size={18}/></span><div><h2 className="font-bold">حریم خصوصی</h2><p className="mt-1 max-w-2xl text-xs leading-6 text-[var(--muted)]">پویا بدون Backend کار می‌کند. پردازش، تبدیل ارز، محاسبه گزارش‌ها و ذخیره‌سازی همگی داخل مرورگر شما انجام می‌شوند و هیچ اطلاعات مالی به سرور ارسال نمی‌شود.</p></div></div></section></div>;
}
