"use client";

import { ChevronDown, ChevronLeft, FolderTree } from "lucide-react";
import { useMemo, useState } from "react";
import { formatMoney, formatPercent, toPersianNumber } from "@/lib/formatters";
import { translateAccountSegment } from "@/lib/account-parser";
import type { CurrencyUnit, Transaction } from "@/lib/types";

interface Node { key: string; label: string; total: number; count: number; children: Map<string, Node> }
function treeFrom(transactions: Transaction[]) { const roots = new Map<string, Node>(); transactions.forEach((t) => { let level = roots; let path = ""; t.account.segments.forEach((segment) => { path = path ? `${path}:${segment}` : segment; let node = level.get(segment); if (!node) { node = { key: path, label: translateAccountSegment(segment), total: 0, count: 0, children: new Map() }; level.set(segment, node); } node.total += Math.abs(t.amountIRR); node.count += 1; level = node.children; }); }); return roots; }

function AccountNode({ node, unit, grand, depth = 0 }: { node: Node; unit: CurrencyUnit; grand: number; depth?: number }) {
  const [open, setOpen] = useState(depth < 1); const children = [...node.children.values()];
  return <div><button onClick={() => children.length && setOpen(!open)} className="grid w-full grid-cols-[minmax(190px,1fr)_140px_140px_90px_80px] items-center gap-3 rounded-[10px] px-3 py-3 text-right text-xs hover:bg-[var(--surface-muted)]" style={{ paddingRight: `${12 + depth * 22}px` }}><span className="flex min-w-0 items-center gap-2">{children.length ? open ? <ChevronDown size={14}/> : <ChevronLeft size={14}/> : <span className="w-3.5"/>}<span className={depth === 0 ? "font-bold" : "truncate"}>{node.label}</span></span><strong className="numbers text-left">{formatMoney(node.total, unit)}</strong><span className="numbers text-left text-[var(--muted)]">{formatMoney(node.total / Math.max(1, node.count), unit)}</span><span className="text-left text-[var(--muted)]">{toPersianNumber(node.count)} تراکنش</span><span className="numbers text-left text-[var(--muted)]">{formatPercent(node.total / Math.max(1, grand) * 100)}</span></button>{open && children.map((child) => <AccountNode key={child.key} node={child} unit={unit} grand={grand} depth={depth + 1}/>)}</div>;
}
export function AccountTree({ transactions, unit }: { transactions: Transaction[]; unit: CurrencyUnit }) { const roots = useMemo(() => treeFrom(transactions), [transactions]); const grand = transactions.reduce((s,t) => s + Math.abs(t.amountIRR), 0); return <section className="card overflow-hidden"><div className="flex items-center gap-3 border-b p-5"><span className="soft-accent flex h-10 w-10 items-center justify-center rounded-[10px]"><FolderTree size={19}/></span><div><h2 className="font-bold">ساختار حساب‌ها</h2><p className="mt-1 text-xs text-[var(--muted)]">مجموع، میانگین، تعداد و سهم هر حساب</p></div></div><div className="overflow-x-auto scrollbar-thin"><div className="min-w-[760px]"><div className="grid grid-cols-[minmax(190px,1fr)_140px_140px_90px_80px] gap-3 bg-[var(--surface-muted)] px-3 py-2.5 text-[10px] text-[var(--muted)]"><span>نام حساب</span><span className="text-left">مجموع</span><span className="text-left">میانگین تراکنش</span><span className="text-left">تعداد</span><span className="text-left">سهم</span></div><div className="p-2">{[...roots.values()].map((node) => <AccountNode key={node.key} node={node} unit={unit} grand={grand}/>)}</div></div></div></section>; }
